# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schematic/schematic_commands.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'schematic/schematic_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.types import base_types_pb2 as common_dot_types_dot_base__types__pb2
from common.types import enums_pb2 as common_dot_types_dot_enums__pb2
from schematic import schematic_types_pb2 as schematic_dot_schematic__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"schematic/schematic_commands.proto\x12\x15kiapi.schematic.types\x1a\x1d\x63ommon/types/base_types.proto\x1a\x18\x63ommon/types/enums.proto\x1a\x1fschematic/schematic_types.proto\"P\n\x15GetSchematicHierarchy\x12\x37\n\x08\x64ocument\x18\x01 \x01(\x0b\x32%.kiapi.common.types.DocumentSpecifier\"\x95\x01\n\x1aSchematicHierarchyResponse\x12\x37\n\x08\x64ocument\x18\x01 \x01(\x0b\x32%.kiapi.common.types.DocumentSpecifier\x12>\n\x10top_level_sheets\x18\x02 \x03(\x0b\x32$.kiapi.schematic.types.SheetInstance\"\x82\x01\n\x13GetSchematicNetlist\x12\x37\n\x08\x64ocument\x18\x01 \x01(\x0b\x32%.kiapi.common.types.DocumentSpecifier\x12\x32\n\x05types\x18\x02 \x03(\x0e\x32#.kiapi.common.types.KiCadObjectType\"\x86\x01\n\x18SchematicNetlistResponse\x12\x37\n\x08\x64ocument\x18\x01 \x01(\x0b\x32%.kiapi.common.types.DocumentSpecifier\x12\x31\n\x04nets\x18\x02 \x03(\x0b\x32#.kiapi.schematic.types.SchematicNetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schematic.schematic_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSCHEMATICHIERARCHY']._serialized_start=151
  _globals['_GETSCHEMATICHIERARCHY']._serialized_end=231
  _globals['_SCHEMATICHIERARCHYRESPONSE']._serialized_start=234
  _globals['_SCHEMATICHIERARCHYRESPONSE']._serialized_end=383
  _globals['_GETSCHEMATICNETLIST']._serialized_start=386
  _globals['_GETSCHEMATICNETLIST']._serialized_end=516
  _globals['_SCHEMATICNETLISTRESPONSE']._serialized_start=519
  _globals['_SCHEMATICNETLISTRESPONSE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
